# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub

name: Publish Docker image with Avahi on remote release

on:
  push:
    branches:
      - main
    #schedule:
    #  - cron: '*/5 * * * *'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    env:
      REMOTE_LATEST_RELEASE: $(curl -s "https://api.github.com/repos/esphome/esphome/releases/latest" | jq -r .tag_name)
      LOCAL_LATEST_RELEASE: $(curl -s "https://api.github.com/repos/vxav/esphome-avahi/releases/latest" | jq -r .tag_name)
    if: env.REMOTE_LATEST_RELEASE != env.LOCAL_LATEST_RELEASE

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: test
        run: echo "VARIABLE_ONE=${{ env.VARIABLE_ONE }}, VARIABLE_TWO=${{ env.VARIABLE_TWO }}."
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: vxav/esphome-avahi:${{ env.REMOTE_LATEST_RELEASE" }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: '.'  # Update with the path to your release artifact
          tag_name: "${{ env.REMOTE_LATEST_RELEASE" }}"
          title: Release ${{ env.REMOTE_LATEST_RELEASE" }}
          body: $(curl -s "https://api.github.com/repos/esphome/esphome/releases/latest" | jq -r .body)
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
